services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: always
    ports:
      - 55001:28015
      - 55000:29015
      - 55002:8080 
     #- ${APP_CLIENT_PORT}:28015
     #- ${APP_CLUSTER_PORT}:29015
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb create --initial-password  
        rethinkdb --bind all
    volumes:
      - rethinkdb_data:/data

volumes:
  rethinkdb_data:

